import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Button } from '@chakra-ui/react';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>Hello this is where the main text for catalyst should be</p>
        <p>CSS can be modified in globals.css in styles</p>
        <p>Any components used should be chakra ui components</p>
        <Button>Like this useless button</Button>
      </main>

      <footer className={styles.footer}>
        <p>
          This is where a footer should be
        </p>
      </footer>
    </div>
  )
}

export default Home
